title: A bjlog
author: Ben Lavelle
email: benjamin.lavelle@btinternet.com
description: > # this means to ignore newlines until "baseurl:"
  A personal page for B Lavelle on github.io. Not much to see here
  for the moment, but one day maybe it'll be the start of a shiny CV.
# social links
facebook_username: benlavelle
github_username:  ben-lavelle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
